name: Shelter tests

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Copy .env file
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: Run composer
        run: |
          composer install --no-interaction

      - name: Create Database
        run: |
          touch database.sqlite

      - name: Run test suite
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database.sqlite
        run: |
          php artisan test

      - name: Run Larastan
        run: |
          ./vendor/bin/phpstan analyse

      - name: Run Pint
        run: |
          ./vendor/bin/pint --test
